# Generated by Django 5.0.3 on 2024-04-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentariya', 'verbose_name_plural': 'Komentariyalar'},
        ),
        migrations.AlterModelOptions(
            name='ega',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='adress',
        ),
    ]
